### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by rolandsteinmeyer** [zvldz/ha_custom_filters#1]
Came here from https://github.com/TheLastProject/lovelace-valetudo-map-card 

where should I put hacs.json ? 
How would I install this with HACS ? Search for custom filters in HACS did not yield anything.

**Comment by zvldz** [comment]
Go to the Integrations page in HACS and select the three dots in the top right corner. Select Custom repositories.
Add repository url. Category - Integration.

https://hacs.xyz/docs/faq/custom_repositories

**Comment by rolandsteinmeyer** [comment]
Ah, ok. Now I can install via HACS. Thanks !
