### ISSUE TITLE
No Issue put a question

### ISSUE THREAD

**Issue by MassakerGU** [zvldz/ha_custom_filters#3]
Hey i found your costume Filter and i want you to ask if you could help me. 
I need to convert a hex string in Home Assistant to Base64. I tried to modify yout filter but no success.
Would be nice if you could help me.

For example: My Hex String is 01000258 and it should be "AQACWA==".

I tried: 
def b64encode(string):
    data = string.encode("UTF-8")
    return base64.b64encode(data)

but no success. 
Would be nice if you could help me. 
Tanks :)

**Comment by zvldz** [comment]
```
import binascii
import base64

hex_val = '01000258'
b64_val = base64.b64encode(binascii.unhexlify(hex_val).decode('utf-8')).decode("utf-8")

print(b64_val)
```

You can create function from it

**Comment by MassakerGU** [comment]
I tried to add the following lines to your costume_component:
def b64encode(string):
    b64_val = base64.b64encode(binascii.unhexlify(string).decode('utf-8')).decode("utf-8")
    return b64_val

but in home assistant i become the error: TypeError: argument should be bytes, buffer or ASCII string, not 'int'
:(

**Comment by MassakerGU** [comment]
I did it thanks. I deleted the first ('utf-8') and now it works. thanks a lot
